LABEL_MAP = {
    "DISTRACTOR":     0,
    "ACTIVE_NEUTRAL": 1,
    "ACTIVE_FORWARD": 2,
    "ACTIVE_LEFT":    3,
    "ACTIVE_RIGHT":   4,
}

FPS = 90
STEP = int(FPS / 10)

MAIN_JOINTS = [
    "Hips", "Spine", "Neck", "Head",
    "LeftUpLeg", "LeftLeg", "RightUpLeg", "RightLeg",
    "LeftArm", "LeftForeArm", "RightArm", "RightForeArm"
]

DISTRACTOR_ID = LABEL_MAP["DISTRACTOR"]

COMMANDS = [LABEL_MAP["ACTIVE_NEUTRAL"],
            LABEL_MAP["ACTIVE_FORWARD"],
            LABEL_MAP["ACTIVE_LEFT"],
            LABEL_MAP["ACTIVE_RIGHT"]]

RANDOM_STATE = 42
WINDOW_SECONDS = 1.0
WINDOW_STEP_SECONDS = STEP / FPS

N_ACTION_PROTOTYPES = 4
N_SUBACTION_PROTOTYPES = 8

NEUTRAL_ID = LABEL_MAP["ACTIVE_NEUTRAL"]
ACTIVE_COMMAND_IDS = (
    LABEL_MAP["ACTIVE_FORWARD"],
    LABEL_MAP["ACTIVE_LEFT"],
    LABEL_MAP["ACTIVE_RIGHT"],
)


MAJORITY_WINDOWS = (1, 3, 5)
CONFIRMATION_WINDOWS = (1, 3, 5)
CONFIDENCE_THRESHOLDS = (0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)


EVENT_IOU_THRESHOLD = 0.50
